
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: python-hw
        image: zoglo/python_hw:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
